### ISSUE TITLE
Name of resource cannot be filled in Khmer language.

### ISSUE THREAD

**Issue by punwath** [OpenDevelopmentMekong/wpckan#233]
There is problem with filling the name of resource in Khmer language. For example, This electricity dataset (https://data.opendevelopmentmekong.net/dataset/electricity-price-and-coverage-areas-in-cambodia?type=dataset) is in English and I want to translate to Khmer. When I fill the resource title in Khmer language and click to update, it is still blank.
![image](https://cloud.githubusercontent.com/assets/18112596/22450670/df757764-e79a-11e6-87b7-026fee68a944.png)

Before click update.

![image](https://cloud.githubusercontent.com/assets/18112596/22450689/fa9ac2f6-e79a-11e6-9d7d-d4157d5ffd24.png)
After click update.

**Comment by acorbi** [comment]
moving to https://github.com/OpenDevelopmentMekong/ckanext-odm_dataset/issues/393

**Comment by acorbi** [comment]
@Huyeng @punwath this should be solved now. please test and cofirm, its already deployed on PROD.

**Comment by punwath** [comment]
Hello @acorbi , This problem is still happening. You may test with this dataset. https://data.opendevelopmentmekong.net/km/dataset/dams-in-cambodia-2008?type=dataset
