### ISSUE TITLE
Bilingual field for agreement template

### ISSUE THREAD

**Issue by punwath** [OpenDevelopmentMekong/wpckan#243]
The bilingual field doesn't work for many fields in agreement template
- Party's obligation in the implementation of the project
- Job creation summary
- Number of created jobs
- Training summary
- Fund allocation for training	
- Environmental protection obligation
-  Socio-cultural protection	
- Fiscal duties summary
- Environmental fund summary
-  Notes
Please make fields bilingual for the text fields.

**Comment by acorbi** [comment]
HI @punwath thanks for raising this. I will implement and deploy within the next hour.

However not all of those fields need to be multilingual. For instance, the numeric fields **Number of created jobs** and **Fund allocation for training** will store numbers which do not need to be localized.

 @prustar ping

**Comment by acorbi** [comment]
fixed via https://github.com/OpenDevelopmentMekong/ckanext-odm_agreement/commit/573d1fbc4bf3a3ab2653ffd88f139c5d0e392eac

**Comment by acorbi** [comment]
@samean @punwath can you confirm that this issue is fixed now and you can continue uploading content?

**Comment by punwath** [comment]
Hello. This problem still happen again.  You can check this example: https://data.opendevelopmentmekong.net/km/agreement/phea-pimex-co-ltd
The fields of English shows in Khmer page and if I edit them, the English page is also changed
